### ISSUE TITLE
Bottom Navigation Bar coming up while entering details using keyboard.

### ISSUE THREAD

**Issue by utsavmajhi** [openMF/mobile-wallet#845] opened 2020-03-22 13:47 UTC
**Summary:**
while opening keyboard to input the values of amt ,the bottom navigation bar comes upward and hiding the fields

**Steps to reproduce:**
-Go to Payments -> Send tab
-Enter amount or Virtual Payment Address.
-observe the bottom navbar. 

**Expected behaviour:**
-Bottom navigation should not come up while entering any input using keyboard.

**Observed behaviour**
-Bottom navbar coming up while opening the keyboard to type.

**Device and Android version:**

Redmi Note 5 Pro
Android 9
Stock Rom

**Screen Recording**
![formatedgif](https://user-images.githubusercontent.com/43748319/77250972-92e7f200-6c71-11ea-95df-d192f51a8be8.gif)

**Comment by dubeyaayush07** [comment] 2020-03-22 15:22
duplicate #774

**Comment by rachittt** [comment] 2020-05-17 21:05
closing this because it is a duplicate of #774

**Closed by rachittt** 2020-05-17 21:05 UTC
