### ISSUE TITLE
Once User Opts for "Forgot passcode login manually" by mistake ends up every time login via username & password

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#480] opened 2019-03-13 10:13 UTC
Once if user has opted for logging "Forgot passcode login manually" even by mistake and we close the app to restart it, this time the app will demand the username and password.

PS: this happened to me when i tried to log in to the app and accidentally clicked on forgot passcode and then inconveniently had to login via username and password

**Comment by RajaVamsi11** [comment] 2019-03-13 12:16
@Vipinsoni38 Please refer [this](https://github.com/openMF/mobile-wallet/issues/327) issue. The solution is proposed to add a confirmational dialog box when clicked on "Forgot passcode login manually" and that is implemented in [this pull request](https://github.com/openMF/mobile-wallet/pull/331). I think it is duplicate of that issue.

**Comment by Vipinsoni38** [comment] 2019-03-13 13:15
i think that is different
because even if you give a dialogue box still it will invalidate pin login and go with only username and password which is not convenient method

**Comment by RajaVamsi11** [comment] 2019-03-13 13:57
@Vipinsoni38 What do you propose a solution to this issue? Once a user forgot his passcode and he wants to log in, the only way to log in is using username and password. As we added a confirmational dialog box when user accidentally press the forgot paascode button he will have a chance to cancel that option.

**Comment by Vipinsoni38** [comment] 2019-03-14 11:10
Just think it that way that you get two methods of sign in 
i think this method seems more comfortable rather than showing dialog box :)

**Comment by RajaVamsi11** [comment] 2019-03-14 12:05
If the user forgot his passcode and he saw two methods of the login in login page he obviously chooses the credentials login rather passcode because he doesn't know his passcode.

**Another example** : If a user newly installed application and he saw two methods of login. The first method is to use username and password (Which he will get at the time of registration) and the second one using passcode which he doesn't know how it works until the first login.
So, In my point of view having two options to login on the login page is not necessary. Let us leave to the mentors to review and continue with the issue.

**Comment by Vipinsoni38** [comment] 2019-03-14 12:08
Hmm Got it.
Cool I'll proceed with another issue 
Thnx @RajaVamsi11 couldn't think that way

**Closed** 2019-03-14 12:08 UTC
