### ISSUE TITLE
Feat: Print the amount in words in receipt fragment 

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#868] opened 2020-04-01 04:46 UTC
**Summary:**

The receipt only displays the amount but many banks display the given amount is words too. I think we need to have that feature.

**Comment by shobhit24** [comment] 2020-04-30 09:59
May I work on this feature?

**Comment by Bhavnaharitsa** [comment] 2020-04-30 14:01
> May I work on this feature?

@shobhit24 Sure, go ahead! :)

**Comment by haran2248** [comment] 2020-07-28 04:22
Can i work on this issue?
Can you tell me in which activity the issue is present?

**Comment by devansh-299** [comment] 2020-07-28 07:08
@haran2248 this issue is not relevant (have a look [here](https://github.com/openMF/mobile-wallet/pull/901#issuecomment-630820747)) and thus I will have to close this issue. Feel free to work on any other open issues.

**Closed by devansh-299** 2020-07-28 07:08 UTC
