### ISSUE TITLE
feat: Read QR from local Storage

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#790] opened 2020-03-03 18:25 UTC
Currently, the user can only scan the QR code.
If a user gets an image that is present inside the local storage this would be better for the user.

**Comment by dubeyaayush07** [comment] 2020-03-04 14:48
Possible duplicate #440

**Comment by rachittt** [comment] 2020-05-19 18:04
duplicate of #440

**Closed by rachittt** 2020-05-19 18:04 UTC
