### ISSUE TITLE
Progress Dialog doesnot closes after operation finished in ReceiptActivity

### ISSUE THREAD

**Issue by ritish099** [openMF/mobile-wallet#1180] opened 2021-01-22 14:17 UTC
**Summary:**

Progress Dialog does not closes after operation finished in ReceiptActivity
**Steps to reproduce:**

Have a fresh installation go to the receipt and click on the download button and give storage permission to the app

**Expected behaviour:**

Progress Dialog should close after the operation is finished

**Observed behavior:**

Progress Dialog is not closing after the operation is finished

**Device and Android version:**

Any

**Screenshots:**

https://user-images.githubusercontent.com/54978105/105501659-8053a480-5cea-11eb-99c2-174131cf893e.mp4

**Comment by devansh-299** [comment] 2021-01-27 07:13
Duplicate of #1116, closing this

**Closed as completed by devansh-299** 2021-01-27 07:13 UTC
