### ISSUE TITLE
Keyboard should be disappear on toggling between Virtual Payment Address and Mobile Number

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#287] opened 2019-02-11 09:54 UTC
**Summary:**

Keyboard should be disappear on toggling between Virtual Payment Address and Mobile Number, in Payments Activity.

**Steps to reproduce:**

- Go to Payments Activity
- Click on Virtual Payment Address
- Click on Mobile Number

**Expected behavior:**

The keyboard should disappear

**Observed behavior:**

The keyboard didn't disappear.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Screenshots:**

![videotogif_2019 02 11_14 23 49](https://user-images.githubusercontent.com/32845033/52553620-1649d980-2e0a-11e9-87fa-e986c5b94d83.gif)
.

**Comment by shaliniv16** [comment] 2019-02-11 09:54
@ankurs287 @luckyman20 Can I work on it?

**Comment by luckyman20** [comment] 2019-02-11 10:59
@shaliniv16 Go ahead.

**Comment by devansh-299** [comment] 2020-01-28 14:11
@luckyman20 can I work on this issue?

**Comment by haran2248** [comment] 2020-07-22 15:08
Can i work on this issue?
@luckyman20

**Comment by luckyman20** [comment] 2020-07-23 07:29
@haran2248 If it still exists, you may.

**Comment by MaskedCarrot** [comment] 2020-08-02 05:08
This issue is not yet resolved. Can I work on it?

**Comment by luckyman20** [comment] 2020-08-03 14:00
I believe @haran2248 isn't working anymore since @haran2248 hasn't replied to this thread. In that case, @Masked-Carrot, you may. But whoever creates the pull request first would be acknowledged.

**Comment by sachin-0102** [comment] 2020-08-18 03:01
The issue is still open, Can I work on it?

**Comment by rchtgpt** [comment] 2020-08-18 04:35
> The issue is still open, Can I work on it?

sorry, there's already a PR for it.

**Comment by AniketNS** [comment] 2023-03-13 15:01
Hey @shaliniv16, can you assign this issue to me? I want to work on this issue.

**Comment by luckyman20** [comment] 2023-03-13 15:54
Fixed in #1026

**Closed by luckyman20** 2023-03-13 15:54 UTC
Labels: First Timers Only
