### ISSUE TITLE
fix: Text aligned in center in Mobile option in Send Fragment

### ISSUE THREAD

**Issue by Bhavnaharitsa** [openMF/mobile-wallet#974] opened 2020-06-12 04:34 UTC
**Summary**
The amount is left-aligned whereas the number in Mobile Number is center aligned which is looking odd. So, I think the text in the mobile number should also be left-aligned.

**Comment by devansh-299** [comment] 2020-06-27 19:08
Duplicate of #366

**Closed as completed by devansh-299** 2020-06-27 19:08 UTC
