### ISSUE TITLE
Display Toast while device not connected to internet

### ISSUE THREAD

**Issue by refactor-droidyy** [openMF/mobile-wallet#691] opened 2020-01-28 19:04 UTC
**Summary:**

While login if the mobile data or wifi is off "Error while login" toast shows.

**Steps to reproduce:**

Try to login without any internet connectivity.

**Expected behavior:**

"Not Connected to Internet " toast should be shows.

**Observed behavior:**

"Error while Login " toast should be shows.

**Device and Android version:**

Android Device - Redmi 4A
Android Version - Android Nougout 7.0.1

**Screenshots:**

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/44283521/73295967-b755be00-422e-11ea-85e5-e1c16b95412d.gif)

**Comment by refactor-droidyy** [comment] 2020-01-28 19:04
@luckyman20 can i work on this ?

**Comment by rachittt** [comment] 2020-01-28 19:20
duplicate of #537

**Closed** 2020-01-28 19:43 UTC
