### ISSUE TITLE
Add Login Validation

### ISSUE THREAD

**Issue by aggarwalpulkit596** [openMF/mobile-wallet#447] opened 2019-03-09 12:48 UTC
**Summary:**
There is no validation of empty string when login in,there should be validation of username and password before making the network call

**Comment by RajaVamsi11** [comment] 2019-03-09 13:40
@aggarwalpulkit596 This is is solved in redesign branch. In the redesign branch, the login button will be enabled only if you enter username and password. Please make sure you check both the branches before you open an issue and start working on this. As the issue is solved is redesign branch there is no need to solve it in dev branch.

**Comment by RajaVamsi11** [comment] 2019-03-09 13:52
@aggarwalpulkit596 As this is solved in redesign branch, you can close this issue.

**Closed** 2019-03-09 13:57 UTC
