### ISSUE TITLE
Bug: Edit Profile dialog crashes when its dismissed

### ISSUE THREAD

**Issue by nirmalhk7** [openMF/mobile-wallet#643] opened 2020-01-08 14:12 UTC
**Summary:**

Pretty much the heading. App crashes when Edit Profile dialog is dismissed and no details are updated.

**Steps to reproduce:**
Go to the View Profile section. Click Edit Profile.
_Do not edit any details_ (doesn't crash when you update details).
Simply press the X (dismiss) button.

**Expected behavior:**
On dismissing the dialog, the dialog should, obviously, be dismissed.

**Observed behavior:**
This is the exact error raised by Android Studio:

`java.lang.RuntimeException: Unable to pause activity {org.mifos.mobilewallet.mifospay/org.mifos.mobilewallet.mifospay.editprofile.ui.EditProfileActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AlertDialog.dismiss()' on a null object reference`

**Device and Android version:**
Android Emulator: Google Pixel 3 running Android 9.

**Comment by nirmalhk7** [comment] 2020-01-08 14:12
I would love to take this issue.

**Comment by rachittt** [comment] 2020-01-08 14:47
hey @nirmalhk7, I am unable to reproduce this issue. The EditProfile dismissal works fine for me. Can you put a screen recording for it ?

**Comment by nirmalhk7** [comment] 2020-01-08 15:37
Here:

![untitled](https://user-images.githubusercontent.com/25480443/71991705-da5a0700-325a-11ea-9c0f-330bfc48f94e.gif)

**Comment by rachittt** [comment] 2020-01-08 16:37
still unable to reproduce it. Did you make any changes to the EditProfile activity on your local branch?

**Comment by nirmalhk7** [comment] 2020-01-08 17:43
That is weird,.. I didn't made no changes to Edit Profile Activity either.

**Comment by luckyman20** [comment] 2020-01-14 08:42
@nirmalhk7 This should be reproducible for everyone. Can you please try it on other devices too?

**Comment by nirmalhk7** [comment] 2020-01-19 05:29
I can confirm that the bug can be experienced on Huawei Honor 8X with Android 9 (Pie), which is the only physical device I could test it on.

**Comment by nirmalhk7** [comment] 2020-02-01 06:28
My PR is ready for merge. Thank you!

**Comment by Sparsh1212** [comment] 2020-12-07 13:35
Is this still up for grab ?

**Comment by ReCodee** [comment] 2020-12-07 14:27
@Sparsh1212 Are you able to reproduce this issue??

**Comment by devansh-299** [comment] 2022-08-20 11:10
This issue has already been solved hence closing this pull request

**Closed by devansh-299** 2022-08-20 11:10 UTC
