### ISSUE TITLE
Mobile Number 

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#366] opened 2019-02-26 20:39 UTC
Summary:
When the mobile number is given as a input it is centre aligned rather then being left aligned which leads to poor user interface .

Expected behavior
Input text in the mobile number field should be left aligned

Observed behavior
Input text in the mobile number field is centre aligned 

Device and Android version:**
Redmi Note 4 
7.0

Screenshots:
![whatsapp image 2019-02-27 at 2 07 12 am](https://user-images.githubusercontent.com/22556185/53444601-a146e880-3a34-11e9-85db-775a0de38c81.jpeg)

**Comment by Anu-123-gif** [comment] 2020-06-27 18:15
@dotrachit can I work on this issue?

**Comment by devansh-299** [comment] 2020-06-27 19:04
> @dotrachit can I work on this issue?

@Anu-123-gif #975 already addresses this problem

**Comment by rdodiya** [comment] 2021-03-04 16:58
Hey @manddy,  I want to contribute but I am getting error message 

"Execution failed for task ':mifospay:packageDebug.
> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $"

while building code .Please help me to solve this error .

**Comment by vrajdesai78** [comment] 2022-03-14 14:39
Can I work on this issue ?

**Comment by devansh-299** [comment] 2022-03-19 06:52
> Can I work on this issue?

Sure, go-ahead

**Comment by vrajdesai78** [comment] 2022-03-19 14:26
I am not able to login into the app. I have tried self-service as username and password as the password.

**Comment by AniketNS** [comment] 2023-03-13 14:58
Hey @manddy, assign this issue to me. I want to work on this issue.

**Comment by rchtgpt** [comment] 2023-06-06 08:15
I was unable to reproduce the issue on my device (Pixel 3 XL API 29). I am closing this PR, assuming that the issue has already been fixed. Please feel free to comment and tag me if you think it needs to be reopened. :smile:

**Closed by rchtgpt** 2023-06-06 08:15 UTC
Labels: First Timers Only
