### ISSUE TITLE
Update new mifos_icon to login screen

### ISSUE THREAD

**Issue by shobhit24** [openMF/mobile-wallet#893] opened 2020-04-15 11:43 UTC
**Summary:**

Summarize your issue here.

**Steps to reproduce:**

How can we reproduce again the issue?

**Expected behavior:**

What did you expect the app to do?

**Observed behavior:**

What did you see instead?  Describe your issue in detail here.

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by devansh-299** [comment] 2020-04-15 13:03
@shobhit24 duplicate of #885

**Comment by shobhit24** [comment] 2020-04-15 13:08
> @shobhit24 duplicate of #885

Oh I see, but why the login screen still having that same old icon?

**Closed** 2020-04-15 13:11 UTC

**Comment by devansh-299** [comment] 2020-04-15 19:09
> 
> 
> > @shobhit24 duplicate of #885
> 
> Oh I see, but why the login screen still having that same old icon?

@shobhit24 because the PR addressing the issue was closed. You can referthe discussion over [here](https://github.com/openMF/mobile-wallet/pull/886)
