### ISSUE TITLE
Redesign:Accounts Tab UI

### ISSUE THREAD

**Issue by manddy** [openMF/mobile-wallet#368] opened 2019-02-26 21:00 UTC
Summary
In the redesign branch the the accounts tab has has the add account button with a bit off text also It is slightly different from the mockups in terms of spacings between the widgets

What did you see instead?  Describe your issue in detail here.

![whatsapp image 2019-02-27 at 2 27 39 am](https://user-images.githubusercontent.com/22556185/53445822-7611c880-3a37-11e9-9d45-59cdd64d65fd.jpeg)

**Comment by haran2248** [comment] 2020-10-02 05:20
I would like to work on this?Is this issue still relevant?

**Comment by devansh-299** [comment] 2022-08-20 11:17
The issue is not relevant anymore hence closing it

**Closed by devansh-299** 2022-08-20 11:17 UTC
